apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idukvrachu-data
  labels:
    app: idukvrachu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-2
  resources:
    requests:
      storage: 1Gi
